backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"   # where uploaded images will go
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Gallery Images"
    folder: "images/uploads"
    create: true
    fields:
      - { name: "image", label: "Image", widget: "image" }
